### ISSUE TITLE
License

### ISSUE THREAD

**Issue by shazron** [gdawg/uiimage-dsp#5]
Thanks for this. I'm wondering what the license is for this code, and if you have decided, you could include a LICENSE file in the repo as well.

**Comment by gdawg** [comment]
I haven't put a license in but feel free to use and abuse it however you wish, there's no warranty of course!

**Comment by gdawg** [comment]
good idea about the license file btw, I've added one!

**Comment by shazron** [comment]
Thanks, I'm afraid that because of the license this lib will be ultimately of no use to people that want to use it for their apps in the iOS app store however, because it is LGPL. All (non-Apple) libraries need to be statically linked in iOS, and if they statically include your lib, they have to open source their code as well because of the LGPL. 

This may be your intent, I don't know, but generally most libraries out there for iOS are either MIT/new BSD/Apache v2.0 licensed, and may require attribution, and that may be enough for most authors. For example, I see in your other project you use JSONKit, which is Apache v2.0 licensed.

**Comment by gdawg** [comment]
Certainly wasn't my intention, I've updated it to use the Apache V2.0 one instead. thx for bringing to my attention.
